framework:
    secret: '%env(APP_SECRET)%'
    session: true

    # Trusted Proxies configuration (only if needed behind a proxy)
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers:
        - 'X-Forwarded-Proto'
        - 'X-Forwarded-Host'
        - 'X-Forwarded-Port'
        - 'X-Forwarded-For'

    default_timezone: 'Europe/Madrid'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
